export const wrp: string;
export const navbarBrand: string;
export const link: string;
export const active: string;
export const container: string;
export const containerContent: string;
export const navbarToggle: string;
export const routeLink: string;
export const navbarHome: string;
